### PR TITLE
Update to work with 2020 gradlerio and image

### PR DESCRIPTION
**Pull request by ThadHouse**
This will only work with the 2020 image, which will be released with beta.
It also updates to enable intellisense with vscode

For vendors, we're working on enabling warnings as errors, so this works around some of the warnings in your code.

### CODE REVIEW

**Comment by ThadHouse** [comment]
@juchong I updated both this and the equivalent in the 448 to use the standard vendor template, rather then using a modified GradleRIO build. This will make it easier for you to stay up to date with changes, and also easier for me to update if necessary. 

The release setup is similar, except instead of running `publish` to generate the output zip, `generateReleaseZip` needs to be explicitly ran. Otherwise, this is basically the same setup.

**Comment by ThadHouse** [comment]
I updated this and the 448 one for beta 3 (Coming out this week)

**Comment by ThadHouse** [comment]
Ok, I updated this to beta 4, which will be the final configuration.

I noticed Stall Configuration was added to the LabVIEW implementation, but I couldn't figure out what changed, and I'm still not sure how to use it or even what its used for. 

We did expose a way to manually get the SPI and SPI DMA FPGA objects out of the HAL so you could develop and figure out what they're actually used for. Once you have that, we can replace the manual calls with a better version, and then remove the manual calls, and add Java support.

https://github.com/wpilibsuite/allwpilib/blob/master/hal/src/main/native/athena/SPI.cpp#L634

These return pointers that you can cast to hal::tSPI and hal::tDMAManager pointers, if you include the "hal/ChipObject.h" header. You can then manually access the configurations and get those things working. Once you do, let me know. If you have something in the next week, we can have something in the kickoff release. Those testing points only work from C++, so you will have no way of configuring them in Java.

@juchong

**Comment by juchong** [comment]
@ThadHouse Sorry for the late reply. The last few months have been insane. The stall configuration adds an adjustable delay between every n bytes transferred using auto SPI. Take a look at the LabVIEW implementation for an example.

**Comment by ThadHouse** [comment]
I saw that, but I couldn't figure out how it was being used, only that it was getting configured. Is that all you need exposed from the wpilib side to do whatever you want to do with it? Thats the part thats confusing me. If all you need is that configuration exposed, and nothing else, I can easily do that.

**Comment by ThadHouse** [comment]
Here's the new API

```
/**
 * Configure the Auto SPI Stall time between reads.
 *
 * @param port The number of the port to use. 0-3 for Onboard CS0-CS2, 4 for
 * MXP.
 * @param csToSclkTicks the number of ticks to wait before asserting the cs pin
 * @param stallTicks the number of ticks to stall for
 * @param pow2BytesPerRead the number of bytes to read before stalling
 */
void HAL_ConfigureSPIAutoStall(HAL_SPIPort port, int32_t csToSclkTicks,
                               int32_t stallTicks, int32_t pow2BytesPerRead,
                               int32_t* status);
```

Hopefully thats enough to do everything you want to do with it.

This PR and the one in the 448 repo are needed to be compatible at least at the base level with 2020.

**Comment by juchong** [comment]
That should be everything needed since the rest is handled in the FPGA. Here's what boosting the sample rate to 400Hz looks like in terms of CPU usage: 

example1

**Pull request merged**
